### ISSUE TITLE
Not Mobile Responsive 

### ISSUE THREAD

**Issue by Debatreya** [Vijaykv5/Unigram#5]
Make Responsive Landing page

**Comment by Vijaykv5** [comment]
@Debatreya Thanks for you Issue!

Are you interested in working on it?

**Comment by Debatreya** [comment]
Yeah. Sure, I am ready to work on this issue. 
But it will take much time atleast a week. 
If that's fine then assign me on it please.

**Comment by Debatreya** [comment]
And I hope you heard about GSSOC, currently they are accepting more projects. So if you are interested then you can add this to GSSOC.
https://www.linkedin.com/posts/girlscriptsoc_gssoc24-opensource-tech-activity-7198942359470927872-0l6c?utm_source=share&utm_medium=member_android

**Comment by Vijaykv5** [comment]
Sure go ahead.

**Comment by Debatreya** [comment]
![1000143257.jpg](https://github.com/Vijaykv5/Unigram/assets/116421305/055df559-742a-4428-841e-234f1164dea5)

How is it? Is it ok? I did the landing page only

**Comment by Vijaykv5** [comment]
Merget in #8
